name: nilm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37_0
  - alabaster=0.7.12=py37_0
  - argh=0.26.2=py37_0
  - astor=0.8.0=py37_0
  - astroid=2.3.3=py37_0
  - astunparse=1.6.3=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - blinker=1.4=py37_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - cachetools=3.1.1=py_0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.4.1=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - docutils=0.16=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - flake8=3.7.9=py37_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37_0
  - gast=0.2.2=py37_0
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.0=py37_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.1=217
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - jedi=0.15.2=py37_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.0=py_1
  - keyring=21.1.1=py37_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.9.3=he6710b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - numpydoc=0.9.2=py_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.2=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_3
  - pluggy=0.13.1=py37_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.11.4=py37he6710b0_0
  - psutil=5.7.0=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.20=py_0
  - pydocstyle=4.0.1=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.10=py37_0
  - pytz=2020.1=py_0
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py37h7b6447c_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.7.0=py_0
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - requests-oauthlib=1.3.0=py_0
  - rope=0.17.0=py_0
  - rsa=4.0=py_0
  - rtree=0.9.4=py37_1
  - scipy=1.4.1=py37h0b6359f_0
  - secretstorage=3.1.2=py37_0
  - setuptools=47.1.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.1.0=py37_0
  - sphinx=3.0.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.3=py37_0
  - spyder-kernels=1.9.1=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.0.0=mkl_py37h66b46cc_0
  - tensorflow-base=2.0.0=mkl_py37h9204916_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - ujson=1.35=py37h14c3975_0
  - urllib3=1.25.8=py37_0
  - watchdog=0.10.2=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - wurlitzer=2.0.0=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/mingjun/anaconda2/envs/nilm

